<?php
// 1. VERIFICAR SE O USUÁRIO ESTÁ LOGADO

// 2. RECUPERAR OS DADOS DO FORMULÁRIO(HTML)
		
// 3. VALIDAR OS DADOS ENVIADOS PELO FORMULÁRIO(VALIDAÇÕES)
	// 3.1. VERIFICAR SE OS CAMPOS OBRIGATORIOS ESTÃO PREENCIDOS
	
	
	// 3.2. VERIFICAR SE AS SENHAS SÃO IGUAIS
		
// 4. TRATAR/PREPARAR OS DADOS PARA O BD
	//NSA

//5. CONECTAR NO BANCO DE DADOS
	

// 6. CRIAR SCRIPT SQL
	
	
// 7. EXECUTAR SCRIPT SQL
		
// 8. TRATAR DADOS RECUPERADOS DO BANCO DE DADOS	
	
// 9. REALIZAR OS PROCESSAMENTOS NECESSÁRIOS (...)

// 10. APRESENTAR OS DADOS
	
// 11. FECHAR CONEXÃO COM O BD
	
?>








